name: sign
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_vector_icons: ^2.0.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/iconApp.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon/iconApp.png"